# Generated by Django 3.2 on 2021-04-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glasnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('broj', models.IntegerField()),
                ('slika', models.ImageField(height_field=500, upload_to='', width_field=300)),
                ('datoteka', models.FileField(upload_to='')),
            ],
        ),
    ]
