# Generated by Django 3.2 on 2021-04-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_glasnici_slika'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glasnici',
            new_name='Glasnik',
        ),
    ]
