# Generated by Django 3.2 on 2021-05-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210422_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glasnik',
            options={'ordering': ['-broj'], 'verbose_name_plural': 'Glasnici'},
        ),
    ]
