# Generated by Django 3.2 on 2021-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Vijesti'},
        ),
        migrations.AddField(
            model_name='post',
            name='sadrzaj',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='slika',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
